name: Sleep Sounds
options:
  deploymentTarget:
    iOS: "16.0"
targets:
  iosApp:
    type: application
    platform: iOS
    sources: [iosApp]
    settings:
      base:
        INFOPLIST_FILE: iosApp/iosApp/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.moxxxskaifa.SleepSoundsPro
    dependencies:
      - framework: composeApp/build/bin/iosArm64/releaseFramework/ComposeApp.framework
        embed: true
