name: Check Compile
on: [push]
jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Install Gradle 8
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.10.2-bin.zip -O /tmp/gradle.zip
          unzip -q /tmp/gradle.zip -d /tmp/gradle
          echo "/tmp/gradle/gradle-8.10.2/bin" >> $GITHUB_PATH
      - name: Android Debug
        run: gradle :composeApp:assembleDebug
