name: Check Compile
on: [push, pull_request]
jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: gradle/actions/setup-gradle@v3
      - name: Compile Android Debug
        run: gradle :composeApp:assembleDebug
      - name: Link iOS Framework
        run: gradle :composeApp:linkDebugFrameworkIosArm64
